---
provisioner:
  playbooks:
    prepare: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/alternative/prepare.yml"
  inventory:
    group_vars:
      all:
        aerospike_exporter_local_cache_path: "/tmp/aerospike_exporter-linux-amd64"
        aerospike_exporter_web_listen_address: '127.0.0.1:8080'
        aerospike_exporter_tls_server_config:
          cert_file: /etc/aerospike_exporter/tls.cert
          key_file: /etc/aerospike_exporter/tls.key
        aerospike_exporter_version: 1.34.0
        aerospike_exporter_binary_url: "https://github.com/prometheus/aerospike_exporter/releases/download/v{{\
                                     \ aerospike_exporter_version }}/aerospike_exporter-{{ aerospike_exporter_version\
                                     \ }}.linux-amd64.tar.gz"
