---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - nvme_exporter
    - install
    - configure
    - run
    - nvme_exporter_install
    - nvme_exporter_configure
    - nvme_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
  vars:
    _common_local_cache_path: "{{ nvme_exporter_local_cache_path }}"
    _common_binaries: "{{ _nvme_exporter_binaries }}"
    _common_binary_install_dir: "{{ nvme_exporter_binary_install_dir }}"
    _common_binary_url: "{{ nvme_exporter_binary_url }}"
    _common_checksums_url: "{{ nvme_exporter_checksums_url }}"
    _common_system_group: "{{ nvme_exporter_system_group }}"
    _common_system_user: "{{ nvme_exporter_system_user }}"
    _common_config_dir: "{{ nvme_exporter_config_dir }}"
  tags:
    - nvme_exporter
    - install
    - nvme_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ ('//' ~ nvme_exporter_web_listen_address) | ansible.builtin.urlsplit('port') }}"
  when: ansible_facts['selinux'].status == "enabled"
  tags:
    - nvme_exporter
    - configure
    - nvme_exporter_configure

- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml
  vars:
    _common_system_user: "{{ nvme_exporter_system_user }}"
    _common_system_group: "{{ nvme_exporter_system_group }}"
    _common_config_dir: "{{ nvme_exporter_config_dir }}"
  tags:
    - nvme_exporter
    - configure
    - nvme_exporter_configure

- name: Ensure NVMe Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nvme_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - nvme_exporter
    - run
    - nvme_exporter_run
