---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus Aerospike Exporter"
    description:
      - "Deploy prometheus L(aerospike_exporter,https://github.com/aerospike/aerospike-prometheus-exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      aerospike_exporter_version:
        description: "Aerospike exporter package version. Also accepts latest as parameter."
        default: "1.34.0"
      aerospike_exporter_binary_url:
        description: "URL of the aerospike_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _aerospike_exporter_repo }}/releases/download/v{{ aerospike_exporter_version }}/aerospike_exporter-{{ aerospike_exporter_version }}.{{ ansible_facts['system'] | lower }}-{{ _aerospike_exporter_go_ansible_arch }}.tar.gz"
      aerospike_exporter_checksums_url:
        description: "URL of the aerospike_exporter checksums file"
        default: "https://github.com/{{ _aerospike_exporter_repo }}/releases/download/v{{ aerospike_exporter_version }}/sha256sums.txt"
      aerospike_exporter_web_listen_address:
        description: "Address on which aerospike_exporter will listen"
        default: "0.0.0.0:9145"
      aerospike_exporter_config_dir:
        description: "Path to directory with aerospike_exporter configuration"
        default: "/etc/aerospike_exporter"
      aerospike_exporter_config_file:
        description: "The filename of the exporter aerospike config file"
        default: "ape.toml"
      aerospike_exporter_host:
        description: "The target Aerospike host"
        default: "localhost"
      aerospike_exporter_port:
        description: "The target Aerospike port"
        default: 3000
      aerospike_exporter_username:
        description: "The username for Aerospike login"
        default: ""
      aerospike_exporter_password:
        description: "The password for Aerospike login"
        default: ""
      aerospike_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(aerospike_exporter docs,https://github.com/aerospike/aerospike-prometheus-exporter/blob/master/https/README.md#sample-config)."
        type: "dict"
      aerospike_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install aerospike_exporter binary"
        default: "/usr/local/bin"
      aerospike_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for Aerospike Exporter"
        default: "aerospike-exp"
      aerospike_exporter_system_user:
        description:
          - "I(Advanced)"
          - "Aerospike Exporter user"
        default: "aerospike-exp"
      aerospike_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/aerospike_exporter-{{ ansible_facts['system'] | lower }}-{{ _aerospike_exporter_go_ansible_arch }}/{{ aerospike_exporter_version }}"
