---
- name: Restart ipmi_exporter
  listen: "restart ipmi_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: ipmi_exporter
    state: restarted
  when:
    - not ansible_check_mode

- name: Reload udev rules
  listen: "reload udev rules"
  become: true
  ansible.builtin.command:
    cmd: udevadm control --reload-rules && udevadm trigger --subsystem-match=ipmi
  changed_when: false
  when:
    - not ansible_check_mode
