---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - nvidia_gpu_exporter_install
        - nvidia_gpu_exporter_configure
        - nvidia_gpu_exporter_run
  tags:
    - nvidia_gpu_exporter_install
    - nvidia_gpu_exporter_configure
    - nvidia_gpu_exporter_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - nvidia_gpu_exporter_install
  when:
    ( not __nvidia_gpu_exporter_is_installed.stat.exists ) or
    ( (__nvidia_gpu_exporter_current_version_output.stderr_lines | length > 0)
      and (__nvidia_gpu_exporter_current_version_output.stderr_lines[0].split(" ")[2] != nvidia_gpu_exporter_version) ) or
    ( (__nvidia_gpu_exporter_current_version_output.stdout_lines | length > 0)
      and (__nvidia_gpu_exporter_current_version_output.stdout_lines[0].split(" ")[2] != nvidia_gpu_exporter_version) ) or
    ( nvidia_gpu_exporter_binary_local_dir | length > 0 )
  tags:
    - nvidia_gpu_exporter_install

- name: SELinux
  ansible.builtin.include_tasks:
    file: selinux.yml
    apply:
      become: true
      tags:
        - nvidia_gpu_exporter_configure
  when: ansible_selinux.status == "enabled"
  tags:
    - nvidia_gpu_exporter_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - nvidia_gpu_exporter_configure
  tags:
    - nvidia_gpu_exporter_configure

- name: Ensure Nvidia GPU Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nvidia_gpu_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - nvidia_gpu_exporter_run
