---
dependency:
  name: galaxy
prerun: false
driver:
  name: docker
platforms:
  - name: almalinux-9
    image: ghcr.io/test-kitchen/dokken/almalinux-9:sha-03eabbc
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: almalinux-10
    image: ghcr.io/test-kitchen/dokken/almalinux-10:sha-03eabbc
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-11
    image: ghcr.io/test-kitchen/dokken/debian-11
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-12
    image: ghcr.io/test-kitchen/dokken/debian-12
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-13
    image: ghcr.io/test-kitchen/dokken/debian-13
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-22.04
    image: ghcr.io/test-kitchen/dokken/ubuntu-22.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-24.04
    image: ghcr.io/test-kitchen/dokken/ubuntu-24.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
verifier:
  name: testinfra
  additional_files_or_dirs:
    - "../../../../../.testinfra/testinfra_helpers.py"
  env:
    PYTHONPATH: "${MOLECULE_PROJECT_DIRECTORY}/../../.testinfra:${PYTHONPATH}"
provisioner:
  env:
    ANSIBLE_INJECT_FACT_VARS: false
  playbooks:
    converge: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/converge.yml"
  inventory:
    hosts:
      target_hosts:
        hosts: {}
    host_vars:
      almalinux-9:
        ansible_become_method: su
      almalinux-10:
        ansible_become_method: su
