---
###
# For each platform be sure to look at the Python version included and filter out
# incompatible versinos from the upstream support table.
#
# https://docs.ansible.com/projects/ansible/latest/reference_appendices/release_and_maintenance.html
#
###
dependency:
  name: galaxy
prerun: false
driver:
  name: docker
platforms:
  - name: almalinux-9
    image: ghcr.io/test-kitchen/dokken/almalinux-9:sha-03eabbc
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: almalinux-10
    image: ghcr.io/test-kitchen/dokken/almalinux-10:sha-03eabbc
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-11
    image: ghcr.io/test-kitchen/dokken/debian-11
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-12
    image: ghcr.io/test-kitchen/dokken/debian-12
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-22.04
    image: ghcr.io/test-kitchen/dokken/ubuntu-22.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-24.04
    image: ghcr.io/test-kitchen/dokken/ubuntu-24.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
verifier:
  name: testinfra
  additional_files_or_dirs:
    - "../../../../../.testinfra/testinfra_helpers.py"
  env:
    PYTHONPATH: "${MOLECULE_PROJECT_DIRECTORY}/../../.testinfra:${PYTHONPATH}"
provisioner:
  env:
    ANSIBLE_INJECT_FACT_VARS: false
  playbooks:
    converge: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/converge.yml"
  inventory:
    hosts:
      target_hosts:
        hosts: {}
    host_vars:
      almalinux-9:
        ansible_become_method: su
        exclude_ansible_vers: ["2.16", "2.17", "2.18", "2.19", "2.20"]
      almalinux-10:
        ansible_become_method: su
        exclude_ansible_vers: ["2.12", "2.13", "2.14", "2.15"]
      debian-11:
        exclude_ansible_vers: ["2.16", "2.17", "2.18", "2.19", "2.20"]
      debian-12:
        exclude_ansible_vers: ["2.12", "2.13", "2.20"]
      ubuntu-22.04:
        exclude_ansible_vers: ["2.12", "2.13", "2.18", "2.19", "2.20"]
      ubuntu-24.04:
        exclude_ansible_vers: ["2.12", "2.13", "2.14", "2.15"]
