---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus NVMe Exporter"
    description:
      - "Deploy prometheus L(NVMe exporter,https://github.com/E4-Computer-Engineering/nvme-exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      nvme_exporter_version:
        description: "NVMe exporter package version. Also accepts latest as parameter."
        default: "3.0.0"
      nvme_exporter_binary_url:
        description: "URL of the NVMe exporter binaries .tar.gz file"
        default: "https://github.com/{{ _nvme_exporter_repo }}/releases/download/v{{ nvme_exporter_version }}/nvme_exporter_{{ nvme_exporter_version }}_{{ ansible_facts['system'] | lower }}_{{ _nvme_exporter_go_ansible_arch }}.tar.gz"
      nvme_exporter_checksums_url:
        description: "URL of the NVMe exporter checksums file"
        default: "https://github.com/{{ _nvme_exporter_repo }}/releases/download/v{{ nvme_exporter_version }}/checksums.txt"
      nvme_exporter_web_listen_address:
        description: "Address on which NVMe exporter will listen"
        default: "0.0.0.0:9998"
      nvme_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      nvme_exporter_disable_defaults:
        description: "Disable all default collectors. Only the collectors listed in O(nvme_exporter_enabled_collectors) will be enabled."
        type: "bool"
        default: false
      nvme_exporter_enabled_collectors:
        description:
          - "List of collectors to enable explicitly (for example C(info), C(smart), C(ocp))."
          - "Mostly useful in combination with O(nvme_exporter_disable_defaults)."
        type: "list"
        elements: "str"
        default: []
      nvme_exporter_disabled_collectors:
        description: "List of collectors to disable explicitly (for example C(ocp))."
        type: "list"
        elements: "str"
        default: []
      nvme_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install nvme_exporter binary"
        default: "/usr/local/bin"
      nvme_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for NVMe exporter"
        default: "nvme-exp"
      nvme_exporter_system_user:
        description:
          - "I(Advanced)"
          - "NVMe exporter user"
        default: "nvme-exp"
      nvme_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/nvme_exporter-{{ ansible_facts['system'] | lower }}-{{ _nvme_exporter_go_ansible_arch }}/{{ nvme_exporter_version }}"
      nvme_exporter_config_dir:
        description: "Path to directory with nvme_exporter configuration"
        default: "/etc/nvme_exporter"
